name = "UKSF-RHS-3CB-BAF-Ammo-Compatibility"
prefix = "UKSFTA"
author = "lErrorl404l"
mainprefix = "z"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "meta.cpp",
]

[version]
major = 1
minor = 0
patch = 0
build = 0
git_hash = 0