name: Arma

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Check for BOM
      uses: arma-actions/bom-check@master
    - name: Checkout the source code
      uses: actions/checkout@main
    - name: Validate Config
      run: python3 tools/config_style_checker.py
    - name: Validate Stringtables
      run: python3 tools/stringtable_validator.py
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Validate Return Types
      run: python3 tools/return_checker.py


  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1
    - name: Run HEMTT build
      run: hemtt build