name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        if: github.repository == 'UKSFTA/UKSF-RHS-3CB-BAF-Ammo-Compatibility'
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}